version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-scheduler-data:/data
    command: redis-server

  api:
    image: prebenorwegian/pnc-api-dev
    restart: always
    env_file:
      - ./config/api.env
    depends_on:
      - redis
    volumes:
      - ./config/jwt-private.key:/server/jwt-private.key
      - ./config/jwt-public.key:/server/jwt-public.key

  webapp:
    image: prebenorwegian/pnc-webapp-dev
    restart: "no"    
    env_file:
      - ./config/webapp.env
    volumes:
      - webapp-static:/app/site

  webcomponents:
    image: prebenorwegian/pnc-webcomponents-dev
    restart: "no"    
    env_file:
      - ./config/webcomponents.env
    volumes:
      - webcomponents-static:/app/webcomponents

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - webapp-static:/app/webapp
      - webcomponents-static:/app/webcomponents
      - nginx-cache-webapp:/pnc_cache/webapp
      - nginx-cache-webcomponents:/pnc_cache/webcomponents
      - ${SSL_CERT}:/ssl/certificate.crt
      - ${SSL_KEY}:/ssl/privkey.key
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - api
      - webapp
      - webcomponents

  watchtower:
    image: containrrr/watchtower
    env_file:
      - ./config/watchtower.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_PATH}:/config.json

volumes: 
  redis-scheduler-data:
  webapp-static:
  webcomponents-static:
  nginx-cache-webapp:
  nginx-cache-webcomponents:
